'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3620
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TKPC.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _return() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("return", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Barcode_Scan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Barcode_Scan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Barcode_Scan_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Barcode_Scan_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bible_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bible-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property booksamo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("booksamo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calculator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property email() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("email", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property list() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("list", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rent1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rent1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reserve() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reserve", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Shipping() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shipping", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tkpc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tkpc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tkpc2009() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tkpc2009", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tkpc2009_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tkpc2009_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tool() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tool", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tool2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tool2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
